import { ActivityType } from '@/typings/activity.type'
import { Category } from '@pom/shared-dtos'
import {
  audioBenefits,
  cerebralBenefits,
  creativeBenefits,
  relaxationBenefits,
  sportyBenefits,
} from './benefitProperties'

export const activity: Record<Category, ActivityType[]> = {
  [Category.SPORTY]: [
    {
      title: 'Activité physique',
      details: 'Effectuer 20 squats',
      duration: 2,
      benefits: sportyBenefits,
      background: 'bg-sporty',
      checkboxColor: 'bg-primary',
      reminderTime: '14:00',
    },
    {
      title: 'Activité physique',
      details: 'Faire 20 pompes',
      duration: 3,
      benefits: sportyBenefits,
      background: 'bg-sporty',
      checkboxColor: 'bg-primary',
      reminderTime: '15:00',
    },
    {
      title: 'Activité physique',
      details: 'Courir 3km',
      duration: 30,
      benefits: sportyBenefits,
      background: 'bg-sporty',
      checkboxColor: 'bg-primary',
      reminderTime: '16:00',
    },
  ],
  [Category.AUDIO]: [
    {
      title: 'Activité Audio',
      details: 'Ecouter un podcast',
      duration: 10,
      benefits: audioBenefits,
      background: 'bg-audio',
      checkboxColor: 'bg-audio-foreground',
      reminderTime: '09:00',
    },
    {
      title: 'Activité Audio',
      details: 'Ecouter une playlist',
      duration: 15,
      benefits: audioBenefits,
      background: 'bg-audio',
      checkboxColor: 'bg-audio-foreground',
      reminderTime: '11:00',
    },
    {
      title: 'Activité Audio',
      details: 'Ecouter une playlist',
      duration: 15,
      benefits: audioBenefits,
      background: 'bg-audio',
      checkboxColor: 'bg-audio-foreground',
      reminderTime: '11:00',
    },
  ],
  [Category.CEREBRAL]: [
    {
      title: 'Activité Cérébrale',
      details: 'Faire un sudoku',
      duration: 5,
      benefits: cerebralBenefits,
      background: 'bg-cerebral',
      checkboxColor: 'bg-cerebral-foreground',
      reminderTime: '08:00',
    },
    {
      title: 'Activité Cérébrale',
      details: 'Résoudre une énigme',
      duration: 10,
      benefits: cerebralBenefits,
      background: 'bg-cerebral',
      checkboxColor: 'bg-cerebral-foreground',
      reminderTime: '17:00',
    },
    {
      title: 'Activité Cérébrale',
      details: 'Résoudre une énigme',
      duration: 10,
      benefits: cerebralBenefits,
      background: 'bg-cerebral',
      checkboxColor: 'bg-cerebral-foreground',
      reminderTime: '17:00',
    },
  ],
  [Category.RELAXATION]: [
    {
      title: 'Activité Relaxante',
      details: 'Faire 5 respirations profondes',
      duration: 2,
      benefits: relaxationBenefits,
      background: 'bg-relaxation',
      checkboxColor: 'bg-relaxation-foreground',
      reminderTime: '18:00',
    },
    {
      title: 'Activité Relaxante',
      details: 'Méditer pendant 10 minutes',
      duration: 10,
      benefits: relaxationBenefits,
      background: 'bg-relaxation',
      checkboxColor: 'bg-relaxation-foreground',
      reminderTime: '19:00',
    },
    {
      title: 'Activité Relaxante',
      details: 'Méditer pendant 10 minutes',
      duration: 10,
      benefits: relaxationBenefits,
      background: 'bg-relaxation',
      checkboxColor: 'bg-relaxation-foreground',
      reminderTime: '19:00',
    },
  ],
  [Category.CREATIVE]: [
    {
      title: 'Activité Créative',
      details: 'Ecrire ses pensées',
      duration: 5,
      benefits: creativeBenefits,
      background: 'bg-creative',
      checkboxColor: 'bg-creative-foreground',
      reminderTime: '16:00',
    },
    {
      title: 'Activité Créative',
      details: 'Dessiner quelque chose',
      duration: 10,
      benefits: creativeBenefits,
      background: 'bg-creative',
      checkboxColor: 'bg-creative-foreground',
      reminderTime: '20:00',
    },
    {
      title: 'Activité Créative',
      details: 'Dessiner quelque chose',
      duration: 10,
      benefits: creativeBenefits,
      background: 'bg-creative',
      checkboxColor: 'bg-creative-foreground',
      reminderTime: '20:00',
    },
  ],
}
